In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import callbacks, layers, models
from tensorflow.keras.utils import to_categorical

import numpy as np

import matplotlib.pyplot as plt
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns

In [2]:
df= pd.read_csv('mental-state.csv')
df.head()

,lag1_mean_0,lag1_mean_1,lag1_mean_2,lag1_mean_3,lag1_mean_d_h2h1_0,lag1_mean_d_h2h1_1,lag1_mean_d_h2h1_2,lag1_mean_d_h2h1_3,lag1_mean_q1_0,lag1_mean_q1_1,...,freq_669_3,freq_679_3,freq_689_3,freq_699_3,freq_709_3,freq_720_3,freq_730_3,freq_740_3,freq_750_3,Label
0,25.781648,33.836367,-92.769629,19.187957,-1.542262,0.197462,-119.561133,2.032654,21.596272,33.965587,...,0.000230,0.000351,0.000547,0.000381,0.000350,0.000453,0.000442,0.000325,0.000209,2.0
1,29.357891,26.792566,417.203910,19.472121,-38.797263,-16.897194,-29.368531,-9.055370,44.647424,40.893307,...,0.001671,0.000740,0.001122,0.000521,0.000624,0.000439,0.001249,0.000727,0.000801,2.0
2,28.451926,31.076434,72.231301,14.245938,-13.225057,-0.614138,-28.331698,-8.858742,31.450289,30.692883,...,0.000748,0.000569,0.000327,0.000197,0.000833,0.000909,0.000699,0.001165,0.000616,2.0
3,21.282184,19.985184,16.220094,39.787312,1.847866,0.670216,-1.820355,20.220724,21.404679,20.777411,...,0.000990,0.005644,0.006891,0.010546,0.009583,0.011158,0.008853,0.004551,0.002287,1.0
4,20.431516,28.982168,27.540246,19.960398,2.491458,-6.020503,-1.071166,2.655259,16.295039,32.658163,...,0.001659,0.014379,0.014492,0.002949,0.004575,0.008305,0.007202,0.006957,0.009836,2.0

In [3]:
df.isna().any()

lag1_mean_0           False
lag1_mean_1           False
lag1_mean_2           False
lag1_mean_3           False
lag1_mean_d_h2h1_0    False
                      ...
freq_720_3            False
freq_730_3            False
freq_740_3            False
freq_750_3            False
Label                 False
Length: 989, dtype: bool

In [4]:
df.describe()

,lag1_mean_0,lag1_mean_1,lag1_mean_2,lag1_mean_3,lag1_mean_d_h2h1_0,lag1_mean_d_h2h1_1,lag1_mean_d_h2h1_2,lag1_mean_d_h2h1_3,lag1_mean_q1_0,lag1_mean_q1_1,...,freq_669_3,freq_679_3,freq_689_3,freq_699_3,freq_709_3,freq_720_3,freq_730_3,freq_740_3,freq_750_3,Label
count,2479.000000,2479.000000,2479.000000,2479.000000,2479.000000,2479.000000,2479.000000,2479.000000,2479.000000,2479.000000,...,2479.000000,2479.000000,2479.000000,2479.000000,2479.000000,2479.000000,2479.000000,2479.000000,2479.000000,2479.000000
mean,23.584351,27.060411,20.452931,11.526044,0.014449,0.003397,0.554037,0.103880,23.271148,26.809551,...,0.008141,0.008063,0.007784,0.007679,0.007413,0.007998,0.007449,0.007307,0.007382,1.004437
std,10.543938,24.252348,72.104439,19.196870,13.382998,39.383221,97.200697,14.461716,17.639164,36.255490,...,0.007653,0.007572,0.007458,0.007276,0.007060,0.007547,0.006937,0.007379,0.007276,0.815743
min,-35.224945,-369.150109,-579.490660,-251.495367,-75.143730,-728.743981,-1048.773622,-96.231800,-351.810178,-800.320690,...,0.000036,0.000024,0.000018,0.000027,0.000052,0.000041,0.000008,0.000036,0.000048,0.000000
25%,18.732076,21.328936,17.124174,6.541236,-4.647636,-3.342428,-6.773096,-4.498267,17.020349,20.684966,...,0.002192,0.002169,0.002108,0.002151,0.001930,0.002034,0.001985,0.002042,0.001964,0.000000
50%,23.553828,27.574535,25.217098,15.144375,-0.140909,0.180963,0.144378,-0.180041,23.761987,27.442672,...,0.006239,0.006029,0.005735,0.005632,0.005532,0.006005,0.005717,0.005300,0.005315,1.000000
75%,27.759551,32.247539,30.746496,20.589852,3.965898,3.594742,7.305102,4.146319,29.574478,32.720855,...,0.011497,0.011610,0.010986,0.011150,0.010645,0.011406,0.010768,0.010208,0.010330,2.000000
max,92.313766,408.180215,591.014113,69.694520,104.963158,512.648208,896.171353,172.660240,116.412065,539.925670,...,0.069699,0.058378,0.086914,0.065296,0.053044,0.054104,0.060196,0.134037,0.071582,2.000000

In [5]:
x=df.drop(['Label'],axis=1)
y=df['Label'].values
print(x.shape)
print(y.shape)

(2479, 988)
(2479,)

In [6]:
# X = df.iloc[:,0:988]
# y = df.iloc[:,-1]

In [7]:
# x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=123)

In [8]:
# x_train.shape

In [9]:
# from tensorflow.keras import Sequential

In [10]:
# model = Sequential()
# model.add(layers.Conv1D(64, 3, input_shape=(x_train.shape[1], 1)))
# model.add(layers.BatchNormalization())
# model.add(layers.MaxPool1D(2))
# model.add(layers.Dropout(0.5))
# model.add(layers.ReLU())
# model.add(layers.Conv1D(filters2, kernel_size2,activation='relu'))

In [11]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2, mutual_info_classif

In [12]:
bestfeatures = SelectKBest(score_func=mutual_info_classif, k=64)
fit = bestfeatures.fit(x,y)

In [13]:
dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(x.columns)

In [14]:
featureScores = pd.concat([dfcolumns,dfscores],axis=1)
featureScores.columns = ['Specs','Score']

In [15]:
featureScores

                  Specs     Score
0           lag1_mean_0  0.174888
1           lag1_mean_1  0.164114
2           lag1_mean_2  0.263016
3           lag1_mean_3  0.179170
4    lag1_mean_d_h2h1_0  0.079852
..                  ...       ...
983          freq_709_3  0.213783
984          freq_720_3  0.269905
985          freq_730_3  0.246393
986          freq_740_3  0.261832
987          freq_750_3  0.239529

[988 rows x 2 columns]

In [16]:
print(featureScores.nlargest(64,'Score'))

               Specs     Score
646       eigenval_0  0.476244
134  lag1_eigenval_0  0.474940
657      logcovM_2_2  0.437961
526            std_2  0.436018
38        lag1_std_2  0.435735
..               ...       ...
820       freq_517_1  0.295012
420  lag1_freq_172_3  0.294284
550         max_q1_2  0.293983
938       freq_233_3  0.292867
934       freq_193_3  0.291930

[64 rows x 2 columns]

In [17]:
top_features=featureScores.nlargest(650,'Score')

In [18]:
scaled_data =(x[top_features])

In [19]:
scaled_data.shape

(2479, 988)

In [20]:
x_train, x_test, y_train, y_test = train_test_split(scaled_data, y, random_state=123, test_size=0.2)

In [21]:
from tensorflow.keras import Sequential

In [22]:
model = Sequential()
model.add(layers.Conv1D(64, 3, input_shape=(x_train.shape[1], 1)))
model.add(layers.BatchNormalization())
model.add(layers.MaxPool1D(2))
model.add(layers.Dropout(0.5))
model.add(layers.ReLU())
    
model.add(layers.Conv1D(64, 5,activation='relu'))
model.add(layers.BatchNormalization())
model.add(layers.MaxPool1D(2))
model.add(layers.Dropout(0.5))
model.add(layers.ReLU())
    
model.add(layers.Conv1D(32, 5,activation='relu'))
model.add(layers.BatchNormalization())
model.add(layers.MaxPool1D(2))
model.add(layers.Dropout(0.5))
model.add(layers.ReLU())
model.add(layers.Flatten())
    
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dropout(0.5))
model.add(layers.Activation('relu'))
model.add(layers.Dense(3, activation='softmax'))
    
model.compile(loss = 'sparse_categorical_crossentropy',optimizer = "adam",metrics = ['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 conv1d (Conv1D)             (None, 986, 64)           256

 batch_normalization (BatchN  (None, 986, 64)          256
 ormalization)

 max_pooling1d (MaxPooling1D  (None, 493, 64)          0
 )

 dropout (Dropout)           (None, 493, 64)           0

 re_lu (ReLU)                (None, 493, 64)           0

 conv1d_1 (Conv1D)           (None, 489, 64)           20544

 batch_normalization_1 (Batc  (None, 489, 64)          256
 hNormalization)

 max_pooling1d_1 (MaxPooling  (None, 244, 64)          0
 1D)

 dropout_1 (Dropout)         (None, 244, 64)           0

 re_lu_1 (ReLU)              (None, 244, 64)           0

 conv1d_2 (Conv1D)           (None, 240, 32)           10272

 batch_normalization_2 (Batc  (None, 240, 32)          128
 hNormalization)

 max_pooling1d_2 (MaxPooling  (None, 120, 32)          0
 1D)

 dropout_2 (Dropout)         (None, 120, 32)           0

 re_lu_2 (ReLU)              (None, 120, 32)           0

 flatten (Flatten)           (None, 3840)              0

 dense (Dense)               (None, 32)                122912

 dropout_3 (Dropout)         (None, 32)                0

 activation (Activation)     (None, 32)                0

 dense_1 (Dense)             (None, 3)                 99

=================================================================
Total params: 154,723
Trainable params: 154,403
Non-trainable params: 320
_________________________________________________________________

In [24]:
model.fit(x_train,y_train,batch_size=300,epochs=30,verbose=1, validation_split=0.25)

Epoch 1/30
5/5 [==============================] - 5s 1s/step - loss: 1.0985 - accuracy: 0.3436 - val_loss: 1.0983 - val_accuracy: 0.3548
Epoch 2/30
5/5 [==============================] - 5s 970ms/step - loss: 1.0985 - accuracy: 0.3436 - val_loss: 1.0983 - val_accuracy: 0.3548
Epoch 3/30
5/5 [==============================] - 5s 946ms/step - loss: 1.0985 - accuracy: 0.3436 - val_loss: 1.0983 - val_accuracy: 0.3548
Epoch 4/30
5/5 [==============================] - 5s 1s/step - loss: 1.0985 - accuracy: 0.3436 - val_loss: 1.0982 - val_accuracy: 0.3548
Epoch 5/30
5/5 [==============================] - 5s 1s/step - loss: 1.0985 - accuracy: 0.3436 - val_loss: 1.0982 - val_accuracy: 0.3548
Epoch 6/30
5/5 [==============================] - 5s 983ms/step - loss: 1.0984 - accuracy: 0.3436 - val_loss: 1.0982 - val_accuracy: 0.3548
Epoch 7/30
5/5 [==============================] - 4s 872ms/step - loss: 1.0984 - accuracy: 0.3436 - val_loss: 1.0982 - val_accuracy: 0.3548
Epoch 8/30
5/5 [==============================] - 5s 976ms/step - loss: 1.0984 - accuracy: 0.3436 - val_loss: 1.0981 - val_accuracy: 0.3548
Epoch 9/30
5/5 [==============================] - 4s 892ms/step - loss: 1.0984 - accuracy: 0.3436 - val_loss: 1.0981 - val_accuracy: 0.3548
Epoch 10/30
5/5 [==============================] - 5s 923ms/step - loss: 1.0984 - accuracy: 0.3436 - val_loss: 1.0981 - val_accuracy: 0.3548
Epoch 11/30
5/5 [==============================] - 4s 911ms/step - loss: 1.0984 - accuracy: 0.3436 - val_loss: 1.0981 - val_accuracy: 0.3548
Epoch 12/30
5/5 [==============================] - 4s 896ms/step - loss: 1.0984 - accuracy: 0.3436 - val_loss: 1.0981 - val_accuracy: 0.3548
Epoch 13/30
5/5 [==============================] - 5s 910ms/step - loss: 1.0984 - accuracy: 0.3436 - val_loss: 1.0981 - val_accuracy: 0.3548
Epoch 14/30
5/5 [==============================] - 4s 875ms/step - loss: 1.0984 - accuracy: 0.3436 - val_loss: 1.0981 - val_accuracy: 0.3548
Epoch 15/30
5/5 [==============================] - 4s 824ms/step - loss: 1.0984 - accuracy: 0.3436 - val_loss: 1.0981 - val_accuracy: 0.3548
Epoch 16/30
5/5 [==============================] - 4s 825ms/step - loss: 1.0984 - accuracy: 0.3436 - val_loss: 1.0981 - val_accuracy: 0.3548
Epoch 17/30
5/5 [==============================] - 4s 837ms/step - loss: 1.0984 - accuracy: 0.3436 - val_loss: 1.0981 - val_accuracy: 0.3548
Epoch 18/30
5/5 [==============================] - 4s 819ms/step - loss: 1.0984 - accuracy: 0.3436 - val_loss: 1.0981 - val_accuracy: 0.3548
Epoch 19/30
5/5 [==============================] - 4s 887ms/step - loss: 1.0984 - accuracy: 0.3436 - val_loss: 1.0981 - val_accuracy: 0.3548
Epoch 20/30
5/5 [==============================] - 4s 845ms/step - loss: 1.0984 - accuracy: 0.3436 - val_loss: 1.0981 - val_accuracy: 0.3548
Epoch 21/30
5/5 [==============================] - 4s 893ms/step - loss: 1.0984 - accuracy: 0.3436 - val_loss: 1.0981 - val_accuracy: 0.3548
Epoch 22/30
5/5 [==============================] - 4s 820ms/step - loss: 1.0984 - accuracy: 0.3436 - val_loss: 1.0981 - val_accuracy: 0.3548
Epoch 23/30
5/5 [==============================] - 4s 813ms/step - loss: 1.0984 - accuracy: 0.3436 - val_loss: 1.0980 - val_accuracy: 0.3548
Epoch 24/30
5/5 [==============================] - 4s 802ms/step - loss: 1.0984 - accuracy: 0.3436 - val_loss: 1.0981 - val_accuracy: 0.3548
Epoch 25/30
5/5 [==============================] - 4s 809ms/step - loss: 1.0984 - accuracy: 0.3436 - val_loss: 1.0981 - val_accuracy: 0.3548
Epoch 26/30
5/5 [==============================] - 4s 818ms/step - loss: 1.0984 - accuracy: 0.3436 - val_loss: 1.0981 - val_accuracy: 0.3548
Epoch 27/30
5/5 [==============================] - 4s 805ms/step - loss: 1.0984 - accuracy: 0.3436 - val_loss: 1.0980 - val_accuracy: 0.3548
Epoch 28/30
5/5 [==============================] - 4s 809ms/step - loss: 1.0984 - accuracy: 0.3436 - val_loss: 1.0981 - val_accuracy: 0.3548
Epoch 29/30
5/5 [==============================] - 4s 808ms/step - loss: 1.0984 - accuracy: 0.3436 - val_loss: 1.0981 - val_accuracy: 0.3548
Epoch 30/30
5/5 [==============================] - 4s 816ms/step - loss: 1.0984 - accuracy: 0.3436 - val_loss: 1.0980 - val_accuracy: 0.3548